# Generated by Django 5.2.13 on 2026-05-05 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NationalStandardBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "std_code",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="国标号"
                    ),
                ),
                (
                    "std_name",
                    models.TextField(blank=True, null=True, verbose_name="标准名称"),
                ),
                (
                    "std_status",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="标准状态"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="发布日期"),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="实施日期"),
                ),
                (
                    "abolition_date",
                    models.DateField(blank=True, null=True, verbose_name="废止日期"),
                ),
                (
                    "std_category",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="标准类别"
                    ),
                ),
                (
                    "replaces_std_code",
                    models.TextField(blank=True, null=True, verbose_name="代替标准"),
                ),
                (
                    "replace_type",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="代替类型"
                    ),
                ),
                (
                    "ccs_code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="中国标准分类号"
                    ),
                ),
                (
                    "ics_code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="国际标准分类号"
                    ),
                ),
                ("ped_id", models.TextField(blank=True, null=True, verbose_name="谱系号")),
                (
                    "detail_url",
                    models.TextField(blank=True, null=True, verbose_name="详情链接"),
                ),
                (
                    "std_file_path",
                    models.TextField(blank=True, null=True, verbose_name="国标文件保存路径"),
                ),
                (
                    "ex_state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="扩展/入库状态（联调用，便于 ex_state 筛选）",
                    ),
                ),
            ],
            options={
                "verbose_name": "国标基础信息",
                "verbose_name_plural": "国标基础信息",
                "db_table": "national_standard_basic",
            },
        ),
        migrations.CreateModel(
            name="NationalStandardExtension",
            fields=[
                (
                    "national_standard",
                    models.OneToOneField(
                        db_column="std_code",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="extension_row",
                        serialize=False,
                        to="standards.nationalstandardbasic",
                        to_field="std_code",
                    ),
                ),
                (
                    "responsible_unit",
                    models.TextField(blank=True, null=True, verbose_name="归口单位/部门"),
                ),
                (
                    "secondary_responsible_unit",
                    models.TextField(blank=True, null=True, verbose_name="副归口单位"),
                ),
                (
                    "issuing_department",
                    models.TextField(blank=True, null=True, verbose_name="颁发部门"),
                ),
                (
                    "executing_unit",
                    models.TextField(blank=True, null=True, verbose_name="执行单位"),
                ),
                (
                    "technical_committee",
                    models.TextField(blank=True, null=True, verbose_name="技术委员会"),
                ),
                (
                    "governing_department",
                    models.TextField(blank=True, null=True, verbose_name="主管部门"),
                ),
                (
                    "adoption_status",
                    models.TextField(blank=True, null=True, verbose_name="采标情况"),
                ),
                (
                    "drafting_unit",
                    models.TextField(blank=True, null=True, verbose_name="起草单位"),
                ),
                (
                    "drafter",
                    models.TextField(blank=True, null=True, verbose_name="起草人"),
                ),
            ],
            options={
                "verbose_name": "国标扩展信息",
                "verbose_name_plural": "国标扩展信息",
                "db_table": "national_standard_extension",
            },
        ),
    ]
