# Generated by Django 5.2.13 on 2026-06-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WarningMonitorRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_evaluated_qb", models.PositiveIntegerField(default=0)),
                ("need_attention_count", models.PositiveIntegerField(default=0)),
                ("all_ok_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "warning_monitor_run",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WarningMonitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qb_code",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "enterprise_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("task_conclusion", models.CharField(db_index=True, max_length=32)),
                ("task_summary", models.TextField(blank=True, default="")),
                ("last_checked_at", models.DateTimeField(db_index=True)),
                ("compare_rows_json", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "warning_monitor_snapshot",
                "ordering": ["-last_checked_at"],
            },
        ),
    ]
