# Generated by Django 5.2.13 on 2026-05-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0002_remove_ex_state_match_mysql_dump"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPedigreeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_std_code",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="起点国标号"
                    ),
                ),
                (
                    "target_std_code",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="终点国标号"
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(max_length=128, verbose_name="关系类型"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "标准谱系关系",
                "verbose_name_plural": "标准谱系关系",
                "db_table": "standard_pedigree_relation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_std_code", "target_std_code"),
                        name="uq_std_pedigree_source_target",
                    )
                ],
            },
        ),
    ]
