# Generated by Django 5.2.13 on 2026-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standards", "0003_standard_pedigree_relation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CcsIndustryClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ccs_code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="中国标准分类号",
                    ),
                ),
                (
                    "ccs_name",
                    models.TextField(blank=True, null=True, verbose_name="名称"),
                ),
                (
                    "parent_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="父代码",
                    ),
                ),
                (
                    "ccs_note",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "CCS 行业分类",
                "verbose_name_plural": "CCS 行业分类",
                "db_table": "ccs_industry_classification",
            },
        ),
        migrations.CreateModel(
            name="IcsIndustryClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ics_code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="国际标准分类号",
                    ),
                ),
                (
                    "ics_level",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="层级"),
                ),
                (
                    "ics_name",
                    models.TextField(blank=True, null=True, verbose_name="名称"),
                ),
                (
                    "ics_note",
                    models.TextField(blank=True, null=True, verbose_name="注释/扩充说明"),
                ),
            ],
            options={
                "verbose_name": "ICS 行业分类",
                "verbose_name_plural": "ICS 行业分类",
                "db_table": "ics_industry_classification",
            },
        ),
    ]
