# Generated by Django 5.2.13 on 2026-06-05 05:34

import django.db.models.deletion
from django.db import migrations, models


def _table_exists(cursor, table: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s
        LIMIT 1
        """,
        [table],
    )
    return cursor.fetchone() is not None


def create_index_import_tables(apps, schema_editor):
    """幂等建表：history 可能已由 v1.0-sql/new_import 导入；job/item 为批量入库新表。"""
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as c:
        if not _table_exists(c, "national_standard_index_import_history"):
            c.execute(
                """
                CREATE TABLE `national_standard_index_import_history` (
                  `id` bigint NOT NULL AUTO_INCREMENT,
                  `std_code` varchar(128) NOT NULL,
                  `original_filename` varchar(512) NOT NULL,
                  `import_status` varchar(32) NOT NULL,
                  `indexes_count` int NOT NULL,
                  `manual_review_status` varchar(32) DEFAULT NULL,
                  `error_message` longtext,
                  `created_at` datetime(6) NOT NULL,
                  `updated_at` datetime(6) NOT NULL,
                  PRIMARY KEY (`id`),
                  KEY `national_st_std_cod_6a8f0d_idx` (`std_code`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                """
            )
        if not _table_exists(c, "national_standard_index_import_job"):
            c.execute(
                """
                CREATE TABLE `national_standard_index_import_job` (
                  `id` bigint NOT NULL AUTO_INCREMENT,
                  `status` varchar(32) NOT NULL,
                  `label` varchar(256) DEFAULT NULL,
                  `total_items` int NOT NULL,
                  `completed_items` int NOT NULL,
                  `failed_items` int NOT NULL,
                  `error_summary` longtext,
                  `created_at` datetime(6) NOT NULL,
                  `updated_at` datetime(6) NOT NULL,
                  PRIMARY KEY (`id`),
                  KEY `national_st_status_8c1f2a_idx` (`status`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                """
            )
        if not _table_exists(c, "national_standard_index_import_item"):
            c.execute(
                """
                CREATE TABLE `national_standard_index_import_item` (
                  `id` bigint NOT NULL AUTO_INCREMENT,
                  `sort_order` int NOT NULL,
                  `original_filename` varchar(512) NOT NULL,
                  `stored_file_path` longtext NOT NULL,
                  `status` varchar(32) NOT NULL,
                  `std_code` varchar(128) DEFAULT NULL,
                  `indexes_count` int NOT NULL,
                  `manual_review_status` varchar(32) DEFAULT NULL,
                  `error_message` longtext,
                  `created_at` datetime(6) NOT NULL,
                  `updated_at` datetime(6) NOT NULL,
                  `job_id` bigint NOT NULL,
                  PRIMARY KEY (`id`),
                  KEY `nsiij_item_job_status` (`job_id`, `status`),
                  KEY `national_st_status_4b9e1c_idx` (`status`),
                  CONSTRAINT `national_standard_index_import_item_job_id_fk`
                    FOREIGN KEY (`job_id`)
                    REFERENCES `national_standard_index_import_job` (`id`)
                    ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                """
            )


class Migration(migrations.Migration):
    dependencies = [
        ("standards", "0006_standardpedigree"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_index_import_tables, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="NationalStandardIndexImportHistory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "std_code",
                            models.CharField(db_index=True, max_length=128, verbose_name="国标号"),
                        ),
                        (
                            "original_filename",
                            models.CharField(max_length=512, verbose_name="上传文件名"),
                        ),
                        (
                            "import_status",
                            models.CharField(
                                choices=[
                                    ("completed", "completed"),
                                    ("failed", "failed"),
                                    ("skipped", "skipped"),
                                ],
                                default="completed",
                                max_length=32,
                                verbose_name="入库状态",
                            ),
                        ),
                        (
                            "indexes_count",
                            models.IntegerField(default=0, verbose_name="indexes 条目数"),
                        ),
                        (
                            "manual_review_status",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("pending", "pending"),
                                    ("approved", "approved"),
                                    ("rejected", "rejected"),
                                ],
                                max_length=32,
                                null=True,
                                verbose_name="人工审核状态",
                            ),
                        ),
                        (
                            "error_message",
                            models.TextField(blank=True, null=True, verbose_name="错误信息"),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                        ),
                    ],
                    options={
                        "verbose_name": "国标指标入库历史",
                        "verbose_name_plural": "国标指标入库历史",
                        "db_table": "national_standard_index_import_history",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="NationalStandardIndexImportJob",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "pending"),
                                    ("processing", "processing"),
                                    ("completed", "completed"),
                                    ("failed", "failed"),
                                ],
                                db_index=True,
                                default="pending",
                                max_length=32,
                                verbose_name="批次状态",
                            ),
                        ),
                        (
                            "label",
                            models.CharField(
                                blank=True, max_length=256, null=True, verbose_name="批次标签"
                            ),
                        ),
                        ("total_items", models.IntegerField(default=0, verbose_name="文件总数")),
                        (
                            "completed_items",
                            models.IntegerField(default=0, verbose_name="已完成数"),
                        ),
                        ("failed_items", models.IntegerField(default=0, verbose_name="失败数")),
                        (
                            "error_summary",
                            models.TextField(blank=True, null=True, verbose_name="批次级错误摘要"),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                        ),
                    ],
                    options={
                        "verbose_name": "国标指标入库批次",
                        "verbose_name_plural": "国标指标入库批次",
                        "db_table": "national_standard_index_import_job",
                        "ordering": ["-id"],
                    },
                ),
                migrations.CreateModel(
                    name="NationalStandardIndexImportItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("sort_order", models.IntegerField(default=0, verbose_name="文件顺序")),
                        (
                            "original_filename",
                            models.CharField(max_length=512, verbose_name="原始文件名"),
                        ),
                        ("stored_file_path", models.TextField(verbose_name="临时存储路径")),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "pending"),
                                    ("running", "running"),
                                    ("completed", "completed"),
                                    ("failed", "failed"),
                                    ("skipped", "skipped"),
                                ],
                                db_index=True,
                                default="pending",
                                max_length=32,
                                verbose_name="条目状态",
                            ),
                        ),
                        (
                            "std_code",
                            models.CharField(
                                blank=True, max_length=128, null=True, verbose_name="国标号"
                            ),
                        ),
                        (
                            "indexes_count",
                            models.IntegerField(default=0, verbose_name="indexes 条目数"),
                        ),
                        (
                            "manual_review_status",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("pending", "待审"),
                                    ("approved", "通过"),
                                    ("rejected", "拒绝"),
                                ],
                                max_length=32,
                                null=True,
                                verbose_name="审核状态",
                            ),
                        ),
                        (
                            "error_message",
                            models.TextField(blank=True, null=True, verbose_name="错误信息"),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                        ),
                        (
                            "job",
                            models.ForeignKey(
                                db_column="job_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="items",
                                to="standards.nationalstandardindeximportjob",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "国标指标入库条目",
                        "verbose_name_plural": "国标指标入库条目",
                        "db_table": "national_standard_index_import_item",
                        "ordering": ["job_id", "sort_order", "id"],
                        "indexes": [
                            models.Index(fields=["job", "status"], name="nsiij_item_job_status")
                        ],
                    },
                ),
            ],
        ),
    ]
