# Generated by Django 5.2.13 on 2026-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0002_compliance_evaluation_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceevaluationtask",
            name="parse_error",
            field=models.TextField(blank=True, help_text="解析失败时的错误摘要", null=True),
        ),
        migrations.AddField(
            model_name="complianceevaluationtask",
            name="parse_status",
            field=models.CharField(
                db_index=True,
                default="completed",
                help_text="企标解析：pending/running/completed/failed；默认 completed 兼容历史同步解析",
                max_length=24,
            ),
        ),
    ]
